"""empty message

Revision ID: ce012246ae1d
Revises: 830f9302cd3b
Create Date: 2019-07-20 18:08:34.210206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce012246ae1d'
down_revision = '830f9302cd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('git_link', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'git_link')
    # ### end Alembic commands ###
